import client from './client'
export const getProjectTasks   = (pid, params) => client.get(`/projects/${pid}/tasks`, { params })
export const createTask        = (pid, data)   => client.post(`/projects/${pid}/tasks`, data)
export const getTask           = (id)           => client.get(`/tasks/${id}`)
export const updateTask        = (id, data)     => client.put(`/tasks/${id}`, data)
export const deleteTask        = (id)           => client.delete(`/tasks/${id}`)
export const addComment        = (tid, data)    => client.post(`/tasks/${tid}/comments`, data)
export const deleteComment     = (cid)          => client.delete(`/comments/${cid}`)
export const getDashboardStats = ()             => client.get('/dashboard/stats')
export const getMyTasks        = ()             => client.get('/dashboard/my-tasks')
export const getUsers          = ()             => client.get('/users')
